# Languages (for more, go to "languages.toml")
# languageCode = "en"
defaultContentLanguage = "en"
baseurl = "developer.nulab-inc.com"
theme = "nulab-inc"
version = "1489528364429"

# This makes the content of the content/backlog route properly
[permalinks]
backlog = "/docs/backlog/api/1/:filename"
cacoo = "/docs/cacoo/api/1/:filename"
typetalk = "/docs/typetalk/api/1/:filename"

# Categorize API by "app"
[taxonomies]
app = "apps"

[languages.en]
weight = 0
languageName = "English"

[[languages.en.menu.main]]
url    = "/"
weight = 0

[languages.ja]
weight = 10
languageName = "Japanese"

[[languages.ja.menu.main]]
url    = "/ja"
weight = 0